services:
  # A Docker web service
  - type: web
    name: Ngrok
    env: docker
    repo: https://github.com/nambarr/rairu-kuns # optional
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: PORT # ngrok port
        value: 22
      - key: JTpvCyHMtDFrLPh2uS54X9omGijRNazqs # ngrok token
        sync: false
